In [1]:
import numpy as np


# ####################################################################
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante método de Gauss-Jordan.
    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)
    else:
        A = A.astype(float)

    assert A.shape[0] == A.shape[1], "La matriz debe ser cuadrada."

    n = A.shape[0]
    I = np.eye(n, dtype=float)
    AI = np.hstack((A, I))  # formar [A | I]

    for i in range(n):
        # --- encontrar pivote
        p = None
        for pi in range(i, n):
            if AI[pi, i] == 0:
                continue
            if p is None or abs(AI[pi, i]) > abs(AI[p, i]):
                p = pi

        if p is None:
            raise ValueError("La matriz no es invertible.")

        if p != i:
            _aux = AI[i, :].copy()
            AI[i, :] = AI[p, :].copy()
            AI[p, :] = _aux

        # --- normalizar pivote
        AI[i, :] = AI[i, :] / AI[i, i]

        # --- eliminar en el resto de filas
        for j in range(n):
            if j == i:
                continue
            m = AI[j, i]
            AI[j, :] = AI[j, :] - m * AI[i, :]

    return AI[:, n:]


# Ejemplo pedido
A = [[2, -3], [-1, 1]]
inv_A = inv_matrix(A)
print(inv_A)

[[-1. -3.]
 [-1. -2.]]


In [ ]:
B = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
inv_matrix(A)
print(inv_matrix(B))

[[-36.  45.  60. -80.]
 [  3.  -4.  -5.   7.]
 [  9. -11. -15.  20.]
 [ 29. -36. -48.  64.]]


In [3]:
C = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
inv_matrix(C)
print(inv_matrix(C))

[[ 2. -1.  0. -1.  0.  2.  2. -1.]
 [ 0.  1.  1. -1.  0.  0.  0.  0.]
 [ 6. -1.  0. -3.  1.  1.  4. -3.]
 [ 6.  1. -1. -3.  1. -3.  3. -3.]
 [ 2. -1.  1. -1.  0.  3.  2. -1.]
 [-2.  2. -0.  0. -0. -4. -2.  1.]
 [-1. -0. -0.  1. -0. -0. -1.  1.]
 [-2. -0. -0.  1. -0. -0. -1.  1.]]


In [4]:
D = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(D)
print(inv_matrix(D))

[[ 14.  -8.   9.  -4.   0.  -4.   9.   7.  -8.   3.]
 [ -2.   2.  -1.   2.   1.   1.  -1.  -1.   1.  -2.]
 [-27.  14. -18.   5.  -2.   7. -17. -13.  16.  -2.]
 [ 12.  -6.   8.  -2.   1.  -3.   7.   6.  -7.   0.]
 [  6.  -4.   4.  -2.   0.  -2.   4.   3.  -3.   2.]
 [ 18.  -9.  12.  -4.   1.  -5.  11.   9. -11.   1.]
 [  8.  -4.   5.  -1.   1.  -2.   5.   4.  -5.   0.]
 [ -5.   2.  -3.   0.  -1.   1.  -3.  -2.   3.   1.]
 [-11.   5.  -7.   1.  -2.   2.  -7.  -5.   7.   1.]
 [  1.  -1.   1.  -1.  -1.  -1.   1.   1.  -1.   1.]]
